export default {
    modes: ["client", "ai", "server", "hotseat", "test", "swrtc", "cwrtc", "ssupa", "csupa", "cauto"],
    mode: "cauto",
    channelTypes: ["socket", "supa", "fake", "auto", "none"],
    channelType: "auto",
    wsPort : 8088,
    logger: "",
    networkDebug: false,
    logicDebug: true,
    fastRestart: false,
    colorOrder: ["blue", "red", "green", "yellow"],
    colors: ["blue", "red", "green", "yellow"],
    color: "blue",
    gameChanPrefix: "sos_",
    playerLimit: 2,
    logLevel: 2,
    idNameInStorage: "my-id",
    idNameLen : 6,
    size: 14
};
