# Simple workflow for deploying static content to GitHub Pages
name: GH Deploy

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    uses: asavan/dev-deps/.github/workflows/deploy.yml@master
    permissions:
      contents: read
      pages: write
      id-token: write
